### PR TITLE
Support PHP

### PR DESCRIPTION
**Pull request by mpkorstanje**
### 🤔 What's changed?

Add support for PHP. 

Fixes:  #18

### ♻️ Anything particular you want feedback on?

Composer only uses tags to work out version numbers (e.g. https://github.com/cucumber/common/blob/main/gherkin/php/default.mk#L29). So we don't even need to have a function for it. Thought it better to explicitly include a no-op.

### CODE REVIEW

**Comment by mattwynne** [comment]
I had a recollection @ciaranmcnulty said that PHP needs a dependency to be in a stand-alone repo (like we used to need for Go). In that case do we need to do anything fancy to push to a mirror repo too?

**Comment by ciaranmcnulty** [comment]
PHP packages normally get their version from git tags. You can do it via a version number in the JSON somehow but that's less common, but we could do it that way I think. I've never tried!

They need composer.json in the root of the repo, and installers will get either a `git clone` or a `.tar.gz` of the whole repo. This is why we put them in a subrepo, it's mostly to save bandwidth (we don't have a compile step so package size is a deployment issue)

**Comment by mpkorstanje** [comment]
Then let's wait until we have a working example of a module using PHP (e.g. Gherkin).

**Comment by ciaranmcnulty** [comment]
here's [the docs for `version` ](https://getcomposer.org/doc/04-schema.md#version) in the composer.json - it's "recommended not to use it"

**Comment by aslakhellesoy** [comment]
I think the `release_php` should push a subtree to a mirror and tag it. Bonus points if it creates that repo if it doesn't exist.

The subtree syncing can be done with something like this (using [git-filter-repo](https://github.com/newren/git-filter-repo)):

```bash
git checkout -b "php-release-$NEW_VERSION"
git filter-repo --subdirectory-filter php --force
git push --force php-mirror "php-release-$NEW_VERSION:main"
```

**Comment by mattwynne** [comment]
> I think the `release_php` should push a subtree to a mirror and tag it. Bonus points if it creates that repo if it doesn't exist.
> 
> The subtree syncing can be done with something like this (using [git-filter-repo](https://github.com/newren/git-filter-repo)):
> 
> ```shell
> git checkout -b "php-release-$NEW_VERSION"
> git filter-repo --subdirectory-filter php --force
> git push --force php-mirror "php-release-$NEW_VERSION:main"
> ```

IMO that's more the responsibility of an `action-publish-php` GitHub action. The less we have running on people's developer machines, the better.

**Pull request merged**
