### PR TITLE
Check for un-pushed/pulled commits

### LINKED ISSUE #43: Check for un-*pulled* git commits
### 🤔 What's the problem you're trying to solve?

Today I was about to release a repo where I'd been merging some PRs via GitHub. I instinctively ran `git status` and saw this:

```
On branch main
Your branch is behind 'origin/main' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean
```

I tried running the command we use in our `check_git_index_clean` and it didn't pick anything up:

```
> multi_test git:(main) git diff-index --quiet HEAD
> echo $?
0
```

### ✨ What's your proposed solution?

Add a pre-flight check for this scenario.

I guess we'd also want to run `git fetch origin` to ensure we had clear sight of all the commits on the remote before we check.

### ⛏ Have you considered any alternatives or workarounds?

I guess we'd end up getting a failure anyway when we try to push our commits to `main` at the end, so we could roll back our "transaction" at that point (i.e. delete the commits we've made to `main`) and print en error to the user, telling them to sort it out by hand.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

### PR DESCRIPTION
**Pull request by mattwynne**
### 🤔 What's changed?

* added a failing test to check for unpushed local commits, to avoid surprises

### ⚡️ What's your motivation? 

So users don't accidentally push local commits when they run this tool.

Fixes #43

### 🏷️ What kind of change is this?

- :zap: New feature (non-breaking change which adds new behaviour)

### ♻️ Anything particular you want feedback on?

I've deliberately only added a failing test so far. I'm thinking that maybe @aurelien-reeves can try implementing the behaviour so he can get a bit familiar with the codebase. I've added the `good-first-issue` label! 😁 

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [ ] I've changed the behaviour of the code
  - [x] I have added/updated tests to cover my changes.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Comment by aurelien-reeves** [comment]
I wanted to give it a try. Here's what happened:

- I cloned the repo and checked out the branch
- Ran `./polyglot-release-test`

More tests are failing than expected. Here's my stdout:

```console
$ ./polyglot-release-test
check-for-changelog.sh Branch 'main' set up to track remote branch 'main' from 'origin'.
✅
check-for-local-commits.sh Branch 'main' set up to track remote branch 'main' from 'origin'.
 🔴

Actual output output different to expected!

/home/aurelien/cucumber/polyglot-release/tests/check-for-local-commits.sh.expected.output
/home/aurelien/cucumber/polyglot-release/tests/check-for-local-commits.sh.actual.output

1,5c1,86
< You have local commits on this branch which are not on origin yet:
< 
< * Add some-file 
< 
< Please push these changes manually before releasing.
\ No newline at end of file
---
> [main 0be0dd4] Add some-file
>  1 file changed, 0 insertions(+), 0 deletions(-)
>  create mode 100644 some-file
> Package manager manifests and CHANGELOG.md updated for 1.0.0
> Here's what changed:
> diff --git a/CHANGELOG.md b/CHANGELOG.md
> index 5c5d610..e849b16 100644
> --- a/CHANGELOG.md
> +++ b/CHANGELOG.md
> @@ -7,12 +7,14 @@ and this project adheres to [Semantic Versioning](http://semver.org/).
>  
>  ## [Unreleased]
>  
> +## [1.0.0] - 2000-01-01
>  ### Fixed
>  - This is a test
>  
>  ## [0.0.1] - 2000-01-01
>  
> -## [0.0.0] - 2000-01-01
> +## 0.0.0 - 2000-01-01
>  
> -[Unreleased]: https://github.com/cucumber/polyglot-release/compare/v0.0.1...main
> +[Unreleased]: https://github.com/cucumber/polyglot-release/compare/v1.0.0...main
> +[1.0.0]: https://github.com/cucumber/polyglot-release/compare/v0.0.1...main
>  [0.0.1]: https://github.com/cucumber/polyglot-release/compare/v0.0.0...v0.0.1
> diff --git a/java/pom.xml b/java/pom.xml
> index 1ddc4c5..6879b6c 100644
> --- a/java/pom.xml
> +++ b/java/pom.xml
> @@ -5,13 +5,13 @@
>  
>      <groupId>com.example</groupId>
>      <artifactId>project</artifactId>
> -    <version>0.0.1-SNAPSHOT</version>
> +    <version>1.0.0</version>
>      <packaging>jar</packaging>
>  
>      <scm>
>          <connection>scm:git:git://github.com/cucumber/polyglot-release.git</connection>
>          <developerConnection>scm:git:git@github.com:cucumber/polyglot-release.git</developerConnection>
>          <url>git://github.com/cucumber/polyglot-release.git</url>
> -        <tag>HEAD</tag>
> +        <tag>v1.0.0</tag>
>      </scm>
>  </project>
> diff --git a/javascript/package-lock.json b/javascript/package-lock.json
> index 2a19e31..67dba24 100644
> --- a/javascript/package-lock.json
> +++ b/javascript/package-lock.json
> @@ -1,12 +1,12 @@
>  {
>    "name": "@example/project",
> -  "version": "0.0.0",
> +  "version": "1.0.0",
>    "lockfileVersion": 2,
>    "requires": true,
>    "packages": {
>      "": {
>        "name": "@example/project",
> -      "version": "0.0.0"
> +      "version": "1.0.0"
>      }
>    }
>  }
> diff --git a/javascript/package.json b/javascript/package.json
> index 806abfd..c37a94d 100644
> --- a/javascript/package.json
> +++ b/javascript/package.json
> @@ -1,4 +1,4 @@
>  {
>    "name": "@example/project",
> -  "version": "0.0.0"
> +  "version": "1.0.0"
>  }
> diff --git a/ruby/VERSION b/ruby/VERSION
> index 77d6f4c..3eefcb9 100644
> --- a/ruby/VERSION
> +++ b/ruby/VERSION
> @@ -1 +1 @@
> -0.0.0
> +1.0.0
> Files committed to to git and tagged 'v1.0.0'
> Post-release changes committed to to git
> All commit(s) pushed to origin/main
> Release commit (tagged with v1.0.0) pushed to origin/release/v1.0.0

Actual git-log output different to expected!

/home/aurelien/cucumber/polyglot-release/tests/check-for-local-commits.sh.expected.git-log
/home/aurelien/cucumber/polyglot-release/tests/check-for-local-commits.sh.actual.git-log

0a1,3
> Prepare for the next development iteration  (HEAD -> main, origin/main)
> Prepare release v1.0.0  (tag: v1.0.0, origin/release/v1.0.0)
> Add some-file 

Examine files in /tmp/tmp.4gnCqVbVVi

check-local-tags.sh Branch 'main' set up to track remote branch 'main' from 'origin'.
✅
check-pwd-is-git-root--in-subdir.sh Branch 'main' set up to track remote branch 'main' from 'origin'.
✅
check-pwd-is-git-root--no-git.sh Branch 'main' set up to track remote branch 'main' from 'origin'.
✅
help.sh Branch 'main' set up to track remote branch 'main' from 'origin'.
 🔴

Actual output output different to expected!

/home/aurelien/cucumber/polyglot-release/tests/help.sh.expected.output
/home/aurelien/cucumber/polyglot-release/tests/help.sh.actual.output

7a8
>   --quiet                don't log progress messages

Examine files in /tmp/tmp.I7pE1ANvpF

missing-version--show-unreleased-changes.sh Branch 'main' set up to track remote branch 'main' from 'origin'.
 🔴

Actual output output different to expected!

/home/aurelien/cucumber/polyglot-release/tests/missing-version--show-unreleased-changes.sh.expected.output
/home/aurelien/cucumber/polyglot-release/tests/missing-version--show-unreleased-changes.sh.actual.output

1,8c1
< Missing MAJOR.MINOR.PATCH argument. Please specify a version to release.
< 
< Usage: polyglot-release [OPTIONS] MAJOR.MINOR.PATCH
< OPTIONS:
<   --help                 shows this help
<   --no-git-push          do not push to git
<   --no-git-commit        do not commit git
<   --only-release         do not update versions after release
---
> Please specify a version to release. Use --help to show usage instructions.

Examine files in /tmp/tmp.6XqC6kKefJ

only-release-javascript.sh Branch 'main' set up to track remote branch 'main' from 'origin'.
✅
only-release-java.sh Branch 'main' set up to track remote branch 'main' from 'origin'.
✅
only-release--no-git-commit.sh Branch 'main' set up to track remote branch 'main' from 'origin'.
✅
only-release-ruby.sh Branch 'main' set up to track remote branch 'main' from 'origin'.
 🔴

Actual git-diff output different to expected!

/home/aurelien/cucumber/polyglot-release/tests/only-release-ruby.sh.expected.git-diff
/home/aurelien/cucumber/polyglot-release/tests/only-release-ruby.sh.actual.git-diff

13,18d12
< diff --git a/VERSION b/VERSION
< --- a/VERSION
< +++ b/VERSION
< @@ -1 +1 @@
< -0.0.0
< +1.0.0

Examine files in /tmp/tmp.LVfr4sfpmD

only-release.sh Branch 'main' set up to track remote branch 'main' from 'origin'.
✅
release--no-git-commit.sh Branch 'main' set up to track remote branch 'main' from 'origin'.
✅
release--no-git-push.sh Branch 'main' set up to track remote branch 'main' from 'origin'.
✅
release.sh Branch 'main' set up to track remote branch 'main' from 'origin'.
✅
try-to-release-ruby-but-no-version-file.sh Branch 'main' set up to track remote branch 'main' from 'origin'.
 🔴

Actual output output different to expected!

/home/aurelien/cucumber/polyglot-release/tests/try-to-release-ruby-but-no-version-file.sh.expected.output
/home/aurelien/cucumber/polyglot-release/tests/try-to-release-ruby-but-no-version-file.sh.actual.output

1c1,23
< This looks like a Ruby project, but there is no VERSION file
---
> Package manager manifests and CHANGELOG.md updated for 1.0.0
> Here's what changed:
> diff --git a/CHANGELOG.md b/CHANGELOG.md
> index 5c5d610..e849b16 100644
> --- a/CHANGELOG.md
> +++ b/CHANGELOG.md
> @@ -7,12 +7,14 @@ and this project adheres to [Semantic Versioning](http://semver.org/).
>  
>  ## [Unreleased]
>  
> +## [1.0.0] - 2000-01-01
>  ### Fixed
>  - This is a test
>  
>  ## [0.0.1] - 2000-01-01
>  
> -## [0.0.0] - 2000-01-01
> +## 0.0.0 - 2000-01-01
>  
> -[Unreleased]: https://github.com/cucumber/polyglot-release/compare/v0.0.1...main
> +[Unreleased]: https://github.com/cucumber/polyglot-release/compare/v1.0.0...main
> +[1.0.0]: https://github.com/cucumber/polyglot-release/compare/v0.0.1...main
>  [0.0.1]: https://github.com/cucumber/polyglot-release/compare/v0.0.0...v0.0.1

Actual exit-status output different to expected!

/home/aurelien/cucumber/polyglot-release/tests/try-to-release-ruby-but-no-version-file.sh.expected.exit-status
/home/aurelien/cucumber/polyglot-release/tests/try-to-release-ruby-but-no-version-file.sh.actual.exit-status

1c1
< 1
---
> 0

Examine files in /tmp/tmp.Cpvn34ef7Q
```

So, I took a look at the `main` branch to see if tests are passing there:

```console
$ git checkout main
Switched to branch 'main'
Your branch is up to date with 'origin/main'.

$ ./polyglot-release-test
./polyglot-release-test: line 4: shellcheck: command not found
```

`shellcheck`: nothing tells us about that in the readme. Fine. I'll install it as I saw in the GHA workflows. Tests are going well.

I go back to `check-for-unpushed-commits` and try to run a single test, the one I want to act on. No documentation on how to do so, I tried a few different commands until I finally find the good one:

```console
$ ./polyglot-release-test tests/check-for-local-commits.sh
check-for-local-commits.sh Branch 'main' set up to track remote branch 'main' from 'origin'.
 🔴

Actual output output different to expected!

/home/aurelien/cucumber/polyglot-release/tests/check-for-local-commits.sh.expected.output
/home/aurelien/cucumber/polyglot-release/tests/check-for-local-commits.sh.actual.output

1,5c1,86
< You have local commits on this branch which are not on origin yet:
< 
< * Add some-file 
< 
< Please push these changes manually before releasing.
\ No newline at end of file
---
> [main da0fa28] Add some-file
>  1 file changed, 0 insertions(+), 0 deletions(-)
>  create mode 100644 some-file
> Package manager manifests and CHANGELOG.md updated for 1.0.0
> Here's what changed:
> diff --git a/CHANGELOG.md b/CHANGELOG.md
> index 5c5d610..e849b16 100644
> --- a/CHANGELOG.md
> +++ b/CHANGELOG.md
> @@ -7,12 +7,14 @@ and this project adheres to [Semantic Versioning](http://semver.org/).
>  
>  ## [Unreleased]
>  
> +## [1.0.0] - 2000-01-01
>  ### Fixed
>  - This is a test
>  
>  ## [0.0.1] - 2000-01-01
>  
> -## [0.0.0] - 2000-01-01
> +## 0.0.0 - 2000-01-01
>  
> -[Unreleased]: https://github.com/cucumber/polyglot-release/compare/v0.0.1...main
> +[Unreleased]: https://github.com/cucumber/polyglot-release/compare/v1.0.0...main
> +[1.0.0]: https://github.com/cucumber/polyglot-release/compare/v0.0.1...main
>  [0.0.1]: https://github.com/cucumber/polyglot-release/compare/v0.0.0...v0.0.1
> diff --git a/java/pom.xml b/java/pom.xml
> index 1ddc4c5..6879b6c 100644
> --- a/java/pom.xml
> +++ b/java/pom.xml
> @@ -5,13 +5,13 @@
>  
>      <groupId>com.example</groupId>
>      <artifactId>project</artifactId>
> -    <version>0.0.1-SNAPSHOT</version>
> +    <version>1.0.0</version>
>      <packaging>jar</packaging>
>  
>      <scm>
>          <connection>scm:git:git://github.com/cucumber/polyglot-release.git</connection>
>          <developerConnection>scm:git:git@github.com:cucumber/polyglot-release.git</developerConnection>
>          <url>git://github.com/cucumber/polyglot-release.git</url>
> -        <tag>HEAD</tag>
> +        <tag>v1.0.0</tag>
>      </scm>
>  </project>
> diff --git a/javascript/package-lock.json b/javascript/package-lock.json
> index 2a19e31..67dba24 100644
> --- a/javascript/package-lock.json
> +++ b/javascript/package-lock.json
> @@ -1,12 +1,12 @@
>  {
>    "name": "@example/project",
> -  "version": "0.0.0",
> +  "version": "1.0.0",
>    "lockfileVersion": 2,
>    "requires": true,
>    "packages": {
>      "": {
>        "name": "@example/project",
> -      "version": "0.0.0"
> +      "version": "1.0.0"
>      }
>    }
>  }
> diff --git a/javascript/package.json b/javascript/package.json
> index 806abfd..c37a94d 100644
> --- a/javascript/package.json
> +++ b/javascript/package.json
> @@ -1,4 +1,4 @@
>  {
>    "name": "@example/project",
> -  "version": "0.0.0"
> +  "version": "1.0.0"
>  }
> diff --git a/ruby/VERSION b/ruby/VERSION
> index 77d6f4c..3eefcb9 100644
> --- a/ruby/VERSION
> +++ b/ruby/VERSION
> @@ -1 +1 @@
> -0.0.0
> +1.0.0
> Files committed to to git and tagged 'v1.0.0'
> Post-release changes committed to to git
> All commit(s) pushed to origin/main
> Release commit (tagged with v1.0.0) pushed to origin/release/v1.0.0

Actual git-log output different to expected!

/home/aurelien/cucumber/polyglot-release/tests/check-for-local-commits.sh.expected.git-log
/home/aurelien/cucumber/polyglot-release/tests/check-for-local-commits.sh.actual.git-log

0a1,3
> Prepare for the next development iteration  (HEAD -> main, origin/main)
> Prepare release v1.0.0  (tag: v1.0.0, origin/release/v1.0.0)
> Add some-file 

Examine files in /tmp/tmp.dtzRlJ0sbU
```

The failure is actually not what I would have expect.
```

As I work on that shell script, I realize that Windows users will have a hard time trying-out to figure how to run it 🤔

**Comment by aurelien-reeves** [comment]
So, I decide to merge main, and *voilà*! 🎉
All tests are green, job done 💪

😅

(should I mention that I absolutely did not implement the requested check?)

**Comment by mattwynne** [comment]
Yes, sorry we didn't leave this branch in a great state, and in fact the tests on `main` weren't working properly as you discovered. That's fixed in https://github.com/cucumber/polyglot-release/pull/50

As for the docs, there are some instructions for running individual tests [here](https://github.com/cucumber/polyglot-release#contributing) but perhaps those should move into a `CONTRIBUTING.md` guide now that the `README` has got longer?

I guess we should also add some docs on what tools you need installed in order to run the tests successfully: basically all the tools the script itself requires, plus `shellcheck`

**Comment by mpkorstanje** [comment]
@mattwynne you can't review this because you made the MR, but can you review it anyway?

**Comment by mattwynne** [comment]
LGTM!

**Comment by mattwynne** [comment]
@mpkorstanje you have to review it yourself for the robot bureaucrats to let us merge it!

**Comment by mattwynne** [comment]
It won't let me add a review.

**Comment by mattwynne** [comment]
\o/

**Comment by mattwynne** [comment]
Want to push the button?

**Comment by mattwynne** [comment]
Done!
We hope you found this email of interest; however, click here if you wish to unsubscribe<http://www2.smartbear.com/SubscriptionCenter.html?utm_source=outlook&utm_medium=email&utm_content=emailsig> or manage your email preferences. Privacy Policy.<https://smartbear.com/privacy/>

Disclaimer

The information contained in this communication from the sender is confidential. It is intended solely for use by the recipient and others authorized to receive it. If you are not the recipient, you are hereby notified that any disclosure, copying, distribution or taking action in relation of the contents of this information is strictly prohibited and may be unlawful.

**Pull request merged**
