### PR TITLE
Add --release-branch-template setting

### PR DESCRIPTION
**Pull request by mattwynne**
### 🤔 What's changed?

* add a `--release-branch-template` setting

### ⚡️ What's your motivation? 

As documented in https://github.com/cucumber/polyglot-release/discussions/20, some people prefer to push to a "pre-release" branch first before doing a proper release.

### 🏷️ What kind of change is this?

- :zap: New feature (non-breaking change which adds new behaviour)

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [x] I've changed the behaviour of the code
  - [x] I have added/updated tests to cover my changes.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Comment by mpkorstanje** [comment]
So what is the workflow here?

It seems that we're stepping away from the idea that one command automates everything and now have to do several manual steps.

I realize this aims to build trust, but it seems overly cautious. We should be able to trust the parts of CI that build the release. The previous commit should be passing and we only change version numbers.

I can accept that you have a different opinion but then this alternative work flow should be documented (somewhere?).

**Comment by mattwynne** [comment]
Personally I plan on using the defaults and pushing directly to the `release/v1.0.0` branch.

@aurelien-reeves prefers to preview his release commit in a PR first and check that CI works on it. I figured this was a good way to allow him to do that but still make use of this too..

I'm not sure we need to document it so much as make it possible. ("Easy things should be easy, hard things should be possible"..?)

**Comment by mattwynne** [comment]
I think part of the issue may be that the manual release instructions encourage the releaser to do dependency upgrades just before making a release. I'm not a fan of that approach - I want releases to be smooth and painless and so I'd like to get any dependency upgrades done beforehand, separately. In that case, as you said Rien, the only changes in the release commit are version numbers.

**Comment by mpkorstanje** [comment]
We should remove those instructions we have renovate bot to do this now.

**Comment by mattwynne** [comment]
> We could remove those instructions we have renovate bot to do this now.

I fully agree. I'd like to discuss this on a Thursday call as I think @aurelien-reeves has a different point of view. I think there are a few repos where maybe Renovate isn't doing a comprehensive job, perhaps where there are pinned dependencies. I'm not sure of the details but we should discuss it.

**Comment by mpkorstanje** [comment]
Then at the very least upgrade the dependencies after the release.

**Pull request closed without merging**
