### PR TITLE
Create release script

### PR DESCRIPTION
**Pull request by mpkorstanje**
### 🤔 What's changed?

Created a script to facilitate the release  process as documented in [RELEASING.md](https://github.com/cucumber/.github/blob/main/RELEASING.md). The script supports java, javascript and ruby.

To install in a project run:

```shell
curl --silent -o release https://raw.githubusercontent.com/cucumber/polyglot-release/main/bootstraper
chmod 744 release
./release --help
```

This the bootstrapper will download the script before execution, keeping it always up to date.

### ⚡️ What's your motivation? 

I suck at following following manual instructions.

### 🏷️ What kind of change is this?

- :zap: New feature (non-breaking change which adds new behaviour)

### ♻️ Anything particular you want feedback on?

 * This project contains rudimentary tests. Could use some setting those up better. And maybe some gitlab CI automation too.
 * The `bootstrapper` requires that we trust the code on `main`. We'll be executing it. How do we manage the gitlab setting so as to make this reliable?

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [x] I've changed the behaviour of the code
  - [x] I have added/updated tests to cover my changes.
- [x] My change requires a change to the documentation.
  - [x] I have updated the documentation accordingly.
- [ ] Users should know about my change
  - [ ] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../CHANGELOG.md), linking to this pull request.

### CODE REVIEW

**Comment by mattwynne** [comment]
Oh nice! I figured you'd gone to bed so carried on making changes in the other place.

**Comment by mattwynne** [comment]
It has tests! 🎉 💖

**Comment by mattwynne** [comment]
> The bootstrapper requires that we trust the code on main. We'll be executing it. How do we manage the gitlab setting so as to make this reliable?

Similar to the `action-release-*` repos, I think we keep the permissions on this repo highly restricted.

**Review by mattwynne — APPROVED** [review]
This is missing a few more changes I made over in `html-formatter` while you were doing this in parallel. I'll merge this and add those as separate PRs.

**Comment by mpkorstanje** [comment]
When we're done I'm going to fix the commit history on main. Squash merge isn't the default yet.

**Comment by mpkorstanje** [comment]
Ah! Didn't see those changes! Nice!

**Pull request merged**
